# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSecurity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
