# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSecurity', '0002_imageupload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
